from fastapi import APIRouter

router = APIRouter(
    prefix="/incidents",
    tags=["Incidents"],
)


# ------------------------------------------------------------
# DEMO INCIDENT
# ------------------------------------------------------------

INCIDENTS = [
    {
        "incident_id": "INC-0001",
        "title": "Possible Denial-of-Service Attack",
        "status": "AWAITING_APPROVAL",
        "severity": "CRITICAL",
        "confidence": 0.9991,
        "risk_score": 93.97,
        "attack_category": "DoS",
        "description": (
            "A high-risk DoS detection generated by the "
            "SentinelAI ML detection pipeline."
        ),
    },
    {
        "incident_id": "INC-0002",
        "title": "Possible Infiltration Activity",
        "status": "AWAITING_APPROVAL",
        "severity": "HIGH",
        "confidence": 0.5474,
        "risk_score": 82.92,
        "attack_category": "Infiltration",
        "description": (
            "A high-risk infiltration detection generated "
            "by the SentinelAI ML detection pipeline."
        ),
    },
]


# ------------------------------------------------------------
# GET ALL INCIDENTS
# ------------------------------------------------------------

@router.get("")
def get_incidents():
    return {
        "incidents": INCIDENTS
    }


# ------------------------------------------------------------
# GET SINGLE INCIDENT
# ------------------------------------------------------------

@router.get("/{incident_id}")
def get_incident(incident_id: str):

    for incident in INCIDENTS:

        if incident["incident_id"] == incident_id:

            return incident

    return {
        "error": "Incident not found"
    }